In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
data = pd.read_csv("Mall_Customers.csv")['Annual_Income_(k$)']

In [3]:
data.describe()

count    200.000000
mean      60.560000
std       26.264721
min       15.000000
25%       41.500000
50%       61.500000
75%       78.000000
max      137.000000
Name: Annual_Income_(k$), dtype: float64

In [4]:
lst = list(random.sample(list(data), k = 40))
for i in lst:
    print(i, end= ",")
# random.sample() is a function, which used simple random sampling without replacement method.

48,40,64,25,103,78,126,93,28,78,63,67,61,59,16,48,19,54,33,29,23,93,71,54,63,103,25,15,77,87,97,40,97,17,78,74,60,88,78,62,

In [5]:
sample_mean = np.mean(lst)
sample_mean

60.85

In [6]:
sample_std = np.std(lst, ddof = 1)
sample_std

28.478106750670136

In [7]:
sample_std/np.sqrt(40)

4.502784039076724

In [8]:
200*64.2

12840.0

In [9]:
np.sqrt(160/8000)*29.5072*200

834.5896485531078

In [10]:
12840.0 - 2.045 * 834.5896485531078

11133.264168708894

In [11]:
Kerala = np.round(np.random.normal(loc=150, scale=15,size=30))
Kerala

array([144., 134., 153., 144., 162., 158., 121., 171., 182., 149., 185.,
       168., 156., 168., 124., 129., 168., 161., 146., 161., 158., 124.,
       153., 159., 141., 160., 147., 148., 153., 155.])

In [12]:
AndhraPradesh = np.round(np.random.normal(loc=120, scale=20, size=25))
AndhraPradesh

array([146., 142., 142., 103., 157., 138., 124., 144., 130., 155., 142.,
        88., 117., 125., 129., 137.,  99., 126., 124., 123., 128., 168.,
       109., 128., 137.])

In [13]:
TamilNadu = np.round(np.random.normal(loc=130, scale=18, size=25))
TamilNadu

array([121., 142., 149., 137.,  89., 151., 140., 172., 137., 115., 151.,
       120.,  99., 130., 131., 127., 126., 152., 141.,  85., 123., 134.,
       154., 116., 116.])

In [14]:
WestBengal = np.round(np.random.normal(loc=150, scale=10, size=10))
WestBengal

array([144., 151., 140., 137., 174., 134., 152., 148., 147., 166.])

In [15]:
Others = np.round(np.random.normal(loc=130, scale=8, size=10))
Others

array([124., 133., 119., 128., 124., 120., 122., 137., 143., 138.])

In [18]:
Kerala.mean(), Kerala.std()

(152.73333333333332, 15.592590833113299)

In [19]:
AndhraPradesh.mean(), AndhraPradesh.std()

(130.44, 17.97126595429493)

In [20]:
TamilNadu.mean(), TamilNadu.std()

(130.32, 20.083266666556014)

In [21]:
WestBengal.mean(), WestBengal.std()

(149.3, 11.857908753233009)

In [22]:
Others.mean(), Others.std()

(128.8, 7.984985911070851)

In [24]:
138.31906 + 1.9842*1.4831

141.26182702

In [26]:
69410 + 1.9842*741.55

70881.38351